version: '3'

services:
  apache:
    image: httpd:latest
    ports:
      - '80:80'
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./log/apache2:/var/log/apache2
  postfix:
    build: ./postfix
    ports:
      - '25:25'
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/master.cf:/etc/postfix/master.cf
      - ./log:/var/log
      - /run/rsyslogd.pid
  mailcatcher:
    build: ./mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
