version: '3'

services:
  fluentd:
    image: fluent/fluentd:v1.14
    volumes:
      - ./fluentd/etc/fluent.conf:/fluentd/etc/fluent.conf
      - ./log/fluentd:/var/log/fluentd
      - ./log/apache2:/var/log/apache2
      - ./log/dummer:/var/log/dummer
    ports:
      - '24224:24224'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
