version: '3'

services:
  fluentbit:
    image: fluent/fluent-bit:1.8
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
      - ./fluent-bit/parsers:/fluent-bit/parsers
      - ./fluent-bit/scripts:/fluent-bit/scripts
      - ./log/fluent-bit:/var/log/fluent-bit
      - ./log/apache2:/var/log/apache2
      - ./log/dummer:/var/log/dummer
    ports:
      - '24224:24224'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 20M
