version: '3'

services:
  dummer:
    build: ./dummer
    stop_signal: SIGTERM
    volumes:
      - ./log/dummer:/var/log/dummer
    links:
      - fluentbit
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-buffer-limit: 100MB
        tag: dummer.stdout
