version: '3'

services:
  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
      - ./fluent-bit/parsers:/fluent-bit/parsers
      - ./fluent-bit/scripts:/fluent-bit/scripts
      - ./log:/var/log
    ports:
      - 24224:24224
  apache:
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./log:/var/log
  postfix:
    build: ./postfix
    ports:
      - 22:22
    volumes:
      - ./log:/var/log    
